version: "1"

services:
    php:
        build:
            context: .docker/php
            args:
                TIMEZONE: ${TIMEZONE}
                PROJECT_ROOT: ${PROJECT_ROOT}
        volumes:
            - ./:${PROJECT_ROOT}
            - ~/.composer:/root/.composer/
            - ./var/docker/log/phpfpm/:/var/log/phpfpm/
            - ./var/docker/log/app/:/var/log/app/
        networks:
            - symfony_app
        extra_hosts:
            - host.docker.internal:host-gateway

networks:
    symfony_app:
